version: '3.1'

services:
  db:
    image: postgres:15
    container_name: support-ticket
    restart: always
    environment:
      POSTGRES_DB: support_ticket_db
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
